services:
  selenium-hub:
    image: selenium/hub:4.33.0-20250606
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"      # Hub の UI と WebDriver

  chrome-node:
    image: selenium/node-chromium:4.33.0-20250606
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
    ports:
      - "5555:5555"      # VNC 用（必要なら）